Adding xz

diff --git a/packages/python-3.10/packaging b/packages/python-3.10/packaging
--- a/packages/python-3.10/packaging
+++ b/packages/python-3.10/packaging
@@ -36,10 +36,23 @@ pushd sqlite-autoconf-3450200
   make install
 popd
 
+echo "Extracting xz-5.6.1.tar.gz ..."
+if ! tar xpvf xz-5.6.1.tar.gz ; then
+  echo "Failed extracting xz-5.6.1.tar.gz ..."
+  exit 1
+fi
+
+echo "Installing xz..."
+pushd xz-5.6.1
+  ./configure --prefix="${BOSH_INSTALL_TARGET}"/extensions
+  make -j $CPUS 
+  make install
+popd
 
 export LDFLAGS=-L${BOSH_INSTALL_TARGET}/extensions/lib
 export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/extensions/include"
 export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/extensions/lib/pkgconfig
+
 
 echo "Building python..."
 pushd Python-3.10.*
