adding xz

diff --git a/packages/python-3.12/packaging b/packages/python-3.12/packaging
--- a/packages/python-3.12/packaging
+++ b/packages/python-3.12/packaging
@@ -27,6 +27,23 @@ export LDFLAGS=-L${BOSH_INSTALL_TARGET}/libffi/lib
 export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/libffi/include"
 export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/libffi/lib/pkgconfig
 
+echo "Extracting xz-5.6.1.tar.gz ..."
+if ! tar xpvf xz-5.6.1.tar.gz ; then
+  echo "Failed extracting xz-5.6.1.tar.gz ..."
+  exit 1
+fi
+
+echo "Installing xz..."
+pushd xz-5.6.1
+  ./configure --prefix="${BOSH_INSTALL_TARGET}"/xz
+  make -j $CPUS 
+  make install
+popd
+
+export LDFLAGS=-L${BOSH_INSTALL_TARGET}/xz/lib
+export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/xz/include"
+export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/xz/lib/pkgconfig
+
 echo "Building python..."
 pushd Python-3.12.*
   ./configure --prefix=$BOSH_INSTALL_TARGET --with-system-ffi
