adding sqlite to install

diff --git a/packages/python-3.12/packaging b/packages/python-3.12/packaging
--- a/packages/python-3.12/packaging
+++ b/packages/python-3.12/packaging
@@ -18,19 +18,32 @@ fi
 
 echo "Installing libffi..."
 pushd libffi-3.4.4
-  ./configure --prefix="${BOSH_INSTALL_TARGET}"/libffi
+  ./configure --prefix="${BOSH_INSTALL_TARGET}"/extensions
   make
   make install
 popd
 
-export LDFLAGS=-L${BOSH_INSTALL_TARGET}/libffi/lib
-export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/libffi/include"
-export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/libffi/lib/pkgconfig
+echo "Extracting sqlite-autoconf-3450200.tar.gz ..."
+if ! tar xpvf sqlite-autoconf-3450200.tar.gz ; then
+  echo "Failed extracting sqlite-autoconf-3450200.tar.gz ..."
+  exit 1
+fi
 
+echo "Installing sqlite..."
+pushd sqlite-autoconf-3450200
+  ./configure --prefix="${BOSH_INSTALL_TARGET}"/extensions
+  make
+  make install
+popd
+
+
+export LDFLAGS=-L${BOSH_INSTALL_TARGET}/extensions/lib
+export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/extensions/include"
+export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/extensions/lib/pkgconfig
 
 echo "Building python..."
 pushd Python-3.12.*
-  ./configure --prefix=$BOSH_INSTALL_TARGET --with-system-ffi
+  ./configure --prefix=$BOSH_INSTALL_TARGET --enable-loadable-sqlite-extensions --enable-optimizations --with-system-ffi
   make -j $CPUS 
   make install
 popd
